#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v25
# autospec commit: 9594167
#
# Source0 file verified with key 0xA5526B9BB3CD4E6A (jdelvare@suse.de)
#
Name     : quilt
Version  : 0.69
Release  : 17
URL      : https://download-mirror.savannah.gnu.org/releases/quilt/quilt-0.69.tar.gz
Source0  : https://download-mirror.savannah.gnu.org/releases/quilt/quilt-0.69.tar.gz
Source1  : https://download-mirror.savannah.gnu.org/releases/quilt/quilt-0.69.tar.gz.sig
Source2  : A5526B9BB3CD4E6A.pkey
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: quilt-bin = %{version}-%{release}
Requires: quilt-data = %{version}-%{release}
Requires: quilt-license = %{version}-%{release}
Requires: quilt-locales = %{version}-%{release}
Requires: quilt-man = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : ed
BuildRequires : gnupg
BuildRequires : util-linux
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
The scripts allow to manage a series of patches by keeping
track of the changes each patch makes. Patches can be
applied, un-applied, refreshed, etc.

The scripts are heavily based on Andrew Morton's patch scripts
found at http://userweb.kernel.org/~akpm/stuff/patch-scripts.tar.gz.

Authors:
--------
    Andrew Morton <akpm@digeo.com>
    Andreas Gruenbacher <agruen@suse.de>

%package bin
Summary: bin components for the quilt package.
Group: Binaries
Requires: quilt-data = %{version}-%{release}
Requires: quilt-license = %{version}-%{release}

%description bin
bin components for the quilt package.


%package data
Summary: data components for the quilt package.
Group: Data

%description data
data components for the quilt package.


%package doc
Summary: doc components for the quilt package.
Group: Documentation
Requires: quilt-man = %{version}-%{release}

%description doc
doc components for the quilt package.


%package license
Summary: license components for the quilt package.
Group: Default

%description license
license components for the quilt package.


%package locales
Summary: locales components for the quilt package.
Group: Default

%description locales
locales components for the quilt package.


%package man
Summary: man components for the quilt package.
Group: Default

%description man
man components for the quilt package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE2}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE1} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) A5526B9BB3CD4E6A' gpg.status
%setup -q -n quilt-0.69
cd %{_builddir}/quilt-0.69
pushd ..
cp -a quilt-0.69 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1745882810
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%configure --disable-static
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../buildavx2;
make %{?_smp_mflags} check || :

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1745882810
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/quilt
cp %{_builddir}/quilt-%{version}/COPYING %{buildroot}/usr/share/package-licenses/quilt/dfac199a7539a404407098a2541b9482279f690d || :
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v2
%make_install
%find_lang quilt
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/guards
/usr/bin/quilt

%files data
%defattr(-,root,root,-)
/usr/share/emacs/site-lisp/quilt.el
/usr/share/quilt/add
/usr/share/quilt/annotate
/usr/share/quilt/applied
/usr/share/quilt/compat/awk
/usr/share/quilt/compat/sendmail
/usr/share/quilt/delete
/usr/share/quilt/diff
/usr/share/quilt/edit
/usr/share/quilt/files
/usr/share/quilt/fold
/usr/share/quilt/fork
/usr/share/quilt/graph
/usr/share/quilt/grep
/usr/share/quilt/header
/usr/share/quilt/import
/usr/share/quilt/mail
/usr/share/quilt/new
/usr/share/quilt/next
/usr/share/quilt/patches
/usr/share/quilt/pop
/usr/share/quilt/previous
/usr/share/quilt/push
/usr/share/quilt/refresh
/usr/share/quilt/remove
/usr/share/quilt/rename
/usr/share/quilt/revert
/usr/share/quilt/scripts/backup-files
/usr/share/quilt/scripts/dependency-graph
/usr/share/quilt/scripts/edmail
/usr/share/quilt/scripts/inspect-wrapper
/usr/share/quilt/scripts/patchfns
/usr/share/quilt/scripts/remove-trailing-ws
/usr/share/quilt/scripts/utilfns
/usr/share/quilt/series
/usr/share/quilt/setup
/usr/share/quilt/snapshot
/usr/share/quilt/spec-filters/obs
/usr/share/quilt/top
/usr/share/quilt/unapplied
/usr/share/quilt/upgrade

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/quilt/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/quilt/dfac199a7539a404407098a2541b9482279f690d

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/guards.1
/usr/share/man/man1/quilt.1

%files locales -f quilt.lang
%defattr(-,root,root,-)

